"""Fixed-order tools for Power-Ringmin quadratic-radii experiments."""

from power_ringmin.crosscheck import SLSQPCheckResult, slsqp_fixed_order
from power_ringmin.evaluator import BindingPair, FullResult, chain_radius, full_radius
from power_ringmin.fixed_order_artifact import (
    ARTIFACT_TYPE,
    SCHEMA_VERSION,
    FixedOrderArtifact,
    artifact_from_full_result,
    artifact_from_highprec_result,
    dump_fixed_order_artifact,
    dumps_fixed_order_artifact,
    export_full_result_artifact,
    export_highprec_artifact,
    load_fixed_order_artifact,
    loads_fixed_order_artifact,
    validate_fixed_order_artifact,
    verifier_payload_from_artifact,
)
from power_ringmin.finite_results import (
    COMMAND_NAME as FINITE_RESULTS_COMMAND_NAME,
    FINITE_RESULTS_SUMMARY_ARTIFACT_TYPE,
    FINITE_RESULTS_SUMMARY_SCHEMA_VERSION,
    FiniteResultsSummary,
    SUMMARY_FORMAT_VERSION as FINITE_RESULTS_SUMMARY_FORMAT_VERSION,
    analyze_checked_finite_results,
    analyze_finite_result_artifact,
    build_finite_results_summary,
    dump_finite_results_summary,
    dumps_finite_results_summary,
    format_finite_results_markdown,
    load_finite_results_summary,
    loads_finite_results_summary,
    validate_finite_results_summary_artifact,
)
from power_ringmin.critical_structure import (
    COMMAND_NAME as CRITICAL_STRUCTURE_COMMAND_NAME,
    CRITICAL_STRUCTURE_ARTIFACT_TYPE,
    CRITICAL_STRUCTURE_SCHEMA_VERSION,
    CriticalStructureAnalysis,
    STRUCTURE_FORMAT_VERSION as CRITICAL_STRUCTURE_FORMAT_VERSION,
    build_critical_structure_analysis,
    dump_critical_structure_analysis,
    dumps_critical_structure_analysis,
    load_critical_structure_analysis,
    loads_critical_structure_analysis,
    normalize_cyclic_signature,
    validate_critical_structure_analysis_artifact,
)
from power_ringmin.geometry import quadratic_radii, theta
from power_ringmin.interval_verifier import (
    FIXED_ORDER_INTERVAL_BRACKET_SCHEMA_VERSION,
    FixedOrderIntervalVerification,
    MPMathIntervalAngularOracle,
    assert_fixed_order_interval_bracket_verified,
    verify_fixed_order_interval_bracket,
)
from power_ringmin.interval_bracket_exporter import (
    FixedOrderIntervalBracketExport,
    build_fixed_order_interval_bracket_record,
    dump_fixed_order_interval_bracket_record,
    dumps_fixed_order_interval_bracket_record,
    export_fixed_order_interval_bracket_record,
    load_fixed_order_interval_bracket_record,
    loads_fixed_order_interval_bracket_record,
)
from power_ringmin.small_n_interval_certificate import (
    COMMAND_NAME as N3_INTERVAL_CERTIFICATE_COMMAND_NAME,
    SMALL_N_COMMAND_NAME as SMALL_N_INTERVAL_CERTIFICATE_COMMAND_NAME,
    SMALL_N_INTERVAL_CERTIFICATE_SCHEMA_VERSION,
    SmallNIntervalCertificate,
    VerifiedLocalIntervalBracket,
    build_n3_interval_certificate_fixture,
    build_small_n_parser,
    build_small_n_interval_certificate,
    dump_small_n_interval_certificate_artifact,
    dumps_small_n_interval_certificate_artifact,
    export_n3_interval_certificate_artifact,
    export_small_n_interval_certificate_artifact,
    load_small_n_interval_certificate_artifact,
    loads_small_n_interval_certificate_artifact,
    validate_small_n_interval_certificate_artifact,
)

__version__ = "0.1.0"

__all__ = [
    "ARTIFACT_TYPE",
    "BindingPair",
    "CRITICAL_STRUCTURE_ARTIFACT_TYPE",
    "CRITICAL_STRUCTURE_COMMAND_NAME",
    "CRITICAL_STRUCTURE_FORMAT_VERSION",
    "CRITICAL_STRUCTURE_SCHEMA_VERSION",
    "CriticalStructureAnalysis",
    "FixedOrderArtifact",
    "FixedOrderIntervalBracketExport",
    "FixedOrderIntervalVerification",
    "FINITE_RESULTS_COMMAND_NAME",
    "FINITE_RESULTS_SUMMARY_ARTIFACT_TYPE",
    "FINITE_RESULTS_SUMMARY_FORMAT_VERSION",
    "FINITE_RESULTS_SUMMARY_SCHEMA_VERSION",
    "FullResult",
    "FIXED_ORDER_INTERVAL_BRACKET_SCHEMA_VERSION",
    "FiniteResultsSummary",
    "MPMathIntervalAngularOracle",
    "N3_INTERVAL_CERTIFICATE_COMMAND_NAME",
    "SMALL_N_INTERVAL_CERTIFICATE_COMMAND_NAME",
    "SCHEMA_VERSION",
    "SMALL_N_INTERVAL_CERTIFICATE_SCHEMA_VERSION",
    "SLSQPCheckResult",
    "SmallNIntervalCertificate",
    "VerifiedLocalIntervalBracket",
    "__version__",
    "assert_fixed_order_interval_bracket_verified",
    "artifact_from_full_result",
    "artifact_from_highprec_result",
    "analyze_checked_finite_results",
    "analyze_finite_result_artifact",
    "build_critical_structure_analysis",
    "build_finite_results_summary",
    "build_n3_interval_certificate_fixture",
    "build_fixed_order_interval_bracket_record",
    "build_small_n_parser",
    "build_small_n_interval_certificate",
    "chain_radius",
    "dump_fixed_order_artifact",
    "dump_fixed_order_interval_bracket_record",
    "dump_critical_structure_analysis",
    "dump_finite_results_summary",
    "dump_small_n_interval_certificate_artifact",
    "dumps_fixed_order_artifact",
    "dumps_fixed_order_interval_bracket_record",
    "dumps_critical_structure_analysis",
    "dumps_finite_results_summary",
    "dumps_small_n_interval_certificate_artifact",
    "export_n3_interval_certificate_artifact",
    "export_small_n_interval_certificate_artifact",
    "export_fixed_order_interval_bracket_record",
    "export_full_result_artifact",
    "export_highprec_artifact",
    "format_finite_results_markdown",
    "full_radius",
    "load_fixed_order_artifact",
    "load_fixed_order_interval_bracket_record",
    "load_critical_structure_analysis",
    "load_finite_results_summary",
    "load_small_n_interval_certificate_artifact",
    "loads_fixed_order_artifact",
    "loads_fixed_order_interval_bracket_record",
    "loads_critical_structure_analysis",
    "loads_finite_results_summary",
    "loads_small_n_interval_certificate_artifact",
    "normalize_cyclic_signature",
    "quadratic_radii",
    "slsqp_fixed_order",
    "theta",
    "validate_fixed_order_artifact",
    "validate_critical_structure_analysis_artifact",
    "validate_finite_results_summary_artifact",
    "validate_small_n_interval_certificate_artifact",
    "verifier_payload_from_artifact",
    "verify_fixed_order_interval_bracket",
]
