"""Fixed-order tools for Power-Ringmin quadratic-radii experiments."""

from power_ringmin.crosscheck import SLSQPCheckResult, slsqp_fixed_order
from power_ringmin.evaluator import BindingPair, FullResult, chain_radius, full_radius
from power_ringmin.fixed_order_artifact import (
    ARTIFACT_TYPE,
    SCHEMA_VERSION,
    FixedOrderArtifact,
    artifact_from_full_result,
    artifact_from_highprec_result,
    dump_fixed_order_artifact,
    dumps_fixed_order_artifact,
    export_full_result_artifact,
    export_highprec_artifact,
    load_fixed_order_artifact,
    loads_fixed_order_artifact,
    validate_fixed_order_artifact,
    verifier_payload_from_artifact,
)
from power_ringmin.geometry import quadratic_radii, theta
from power_ringmin.interval_verifier import (
    FIXED_ORDER_INTERVAL_BRACKET_SCHEMA_VERSION,
    FixedOrderIntervalVerification,
    MPMathIntervalAngularOracle,
    assert_fixed_order_interval_bracket_verified,
    verify_fixed_order_interval_bracket,
)
from power_ringmin.interval_bracket_exporter import (
    FixedOrderIntervalBracketExport,
    build_fixed_order_interval_bracket_record,
    dump_fixed_order_interval_bracket_record,
    dumps_fixed_order_interval_bracket_record,
    export_fixed_order_interval_bracket_record,
    load_fixed_order_interval_bracket_record,
    loads_fixed_order_interval_bracket_record,
)
from power_ringmin.small_n_interval_certificate import (
    SMALL_N_INTERVAL_CERTIFICATE_SCHEMA_VERSION,
    SmallNIntervalCertificate,
    VerifiedLocalIntervalBracket,
    build_n3_interval_certificate_fixture,
    build_small_n_interval_certificate,
    dump_small_n_interval_certificate_artifact,
    dumps_small_n_interval_certificate_artifact,
    load_small_n_interval_certificate_artifact,
    loads_small_n_interval_certificate_artifact,
    validate_small_n_interval_certificate_artifact,
)

__version__ = "0.1.0"

__all__ = [
    "ARTIFACT_TYPE",
    "BindingPair",
    "FixedOrderArtifact",
    "FixedOrderIntervalBracketExport",
    "FixedOrderIntervalVerification",
    "FullResult",
    "FIXED_ORDER_INTERVAL_BRACKET_SCHEMA_VERSION",
    "MPMathIntervalAngularOracle",
    "SCHEMA_VERSION",
    "SMALL_N_INTERVAL_CERTIFICATE_SCHEMA_VERSION",
    "SLSQPCheckResult",
    "SmallNIntervalCertificate",
    "VerifiedLocalIntervalBracket",
    "__version__",
    "assert_fixed_order_interval_bracket_verified",
    "artifact_from_full_result",
    "artifact_from_highprec_result",
    "build_n3_interval_certificate_fixture",
    "build_fixed_order_interval_bracket_record",
    "build_small_n_interval_certificate",
    "chain_radius",
    "dump_fixed_order_artifact",
    "dump_fixed_order_interval_bracket_record",
    "dump_small_n_interval_certificate_artifact",
    "dumps_fixed_order_artifact",
    "dumps_fixed_order_interval_bracket_record",
    "dumps_small_n_interval_certificate_artifact",
    "export_fixed_order_interval_bracket_record",
    "export_full_result_artifact",
    "export_highprec_artifact",
    "full_radius",
    "load_fixed_order_artifact",
    "load_fixed_order_interval_bracket_record",
    "load_small_n_interval_certificate_artifact",
    "loads_fixed_order_artifact",
    "loads_fixed_order_interval_bracket_record",
    "loads_small_n_interval_certificate_artifact",
    "quadratic_radii",
    "slsqp_fixed_order",
    "theta",
    "validate_fixed_order_artifact",
    "validate_small_n_interval_certificate_artifact",
    "verifier_payload_from_artifact",
    "verify_fixed_order_interval_bracket",
]
